syntax = "proto3";
option java_multiple_files = true;
package org.baeldung.grpc;

message HelloRequest {
    string firstName = 1;
    string lastName = 2;
    enum Language {
        EN = 0;
        FR = 1;
        AR = 2;
    }
    Language lang = 3; // Language choice
}

message HelloResponse {
    string greeting = 1;
}

service HelloService {
    // Unary RPC
    rpc hello(HelloRequest) returns (HelloResponse);

    // Server streaming: sends multiple greeting messages
    rpc helloStream(HelloRequest) returns (stream HelloResponse);
}