// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto

#include "hello.pb.h"
#include "hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace org {
namespace baeldung {
namespace grpc {

static const char* HelloService_method_names[] = {
  "/org.baeldung.grpc.HelloService/hello",
};

std::unique_ptr< HelloService::Stub> HelloService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HelloService::Stub> stub(new HelloService::Stub(channel));
  return stub;
}

HelloService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_hello_(HelloService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HelloService::Stub::hello(::grpc::ClientContext* context, const ::org::baeldung::grpc::HelloRequest& request, ::org::baeldung::grpc::HelloResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_hello_, context, request, response);
}

void HelloService::Stub::experimental_async::hello(::grpc::ClientContext* context, const ::org::baeldung::grpc::HelloRequest* request, ::org::baeldung::grpc::HelloResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, std::move(f));
}

void HelloService::Stub::experimental_async::hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::org::baeldung::grpc::HelloResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, std::move(f));
}

void HelloService::Stub::experimental_async::hello(::grpc::ClientContext* context, const ::org::baeldung::grpc::HelloRequest* request, ::org::baeldung::grpc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, reactor);
}

void HelloService::Stub::experimental_async::hello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::org::baeldung::grpc::HelloResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_hello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::org::baeldung::grpc::HelloResponse>* HelloService::Stub::AsynchelloRaw(::grpc::ClientContext* context, const ::org::baeldung::grpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::org::baeldung::grpc::HelloResponse>::Create(channel_.get(), cq, rpcmethod_hello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::org::baeldung::grpc::HelloResponse>* HelloService::Stub::PrepareAsynchelloRaw(::grpc::ClientContext* context, const ::org::baeldung::grpc::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::org::baeldung::grpc::HelloResponse>::Create(channel_.get(), cq, rpcmethod_hello_, context, request, false);
}

HelloService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HelloService::Service, ::org::baeldung::grpc::HelloRequest, ::org::baeldung::grpc::HelloResponse>(
          [](HelloService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::org::baeldung::grpc::HelloRequest* req,
             ::org::baeldung::grpc::HelloResponse* resp) {
               return service->hello(ctx, req, resp);
             }, this)));
}

HelloService::Service::~Service() {
}

::grpc::Status HelloService::Service::hello(::grpc::ServerContext* context, const ::org::baeldung::grpc::HelloRequest* request, ::org::baeldung::grpc::HelloResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace org
}  // namespace baeldung
}  // namespace grpc

