// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package org.baeldung.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.baeldung.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <pre>
   * Language choice
   * </pre>
   *
   * <code>.org.baeldung.grpc.HelloRequest.Language lang = 3;</code>
   * @return The enum numeric value on the wire for lang.
   */
  int getLangValue();
  /**
   * <pre>
   * Language choice
   * </pre>
   *
   * <code>.org.baeldung.grpc.HelloRequest.Language lang = 3;</code>
   * @return The lang.
   */
  org.baeldung.grpc.HelloRequest.Language getLang();
}
