// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package org.baeldung.grpc;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_baeldung_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_baeldung_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_baeldung_grpc_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_baeldung_grpc_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\021org.baeldung.grpc\"\217\001\n\014Hel" +
      "loRequest\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName" +
      "\030\002 \001(\t\0226\n\004lang\030\003 \001(\0162(.org.baeldung.grpc" +
      ".HelloRequest.Language\"\"\n\010Language\022\006\n\002EN" +
      "\020\000\022\006\n\002FR\020\001\022\006\n\002AR\020\002\"!\n\rHelloResponse\022\020\n\010g" +
      "reeting\030\001 \001(\t2\256\001\n\014HelloService\022J\n\005hello\022" +
      "\037.org.baeldung.grpc.HelloRequest\032 .org.b" +
      "aeldung.grpc.HelloResponse\022R\n\013helloStrea" +
      "m\022\037.org.baeldung.grpc.HelloRequest\032 .org" +
      ".baeldung.grpc.HelloResponse0\001B\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_baeldung_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_baeldung_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_baeldung_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Lang", });
    internal_static_org_baeldung_grpc_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_baeldung_grpc_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_baeldung_grpc_HelloResponse_descriptor,
        new java.lang.String[] { "Greeting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
