# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x11org.baeldung.grpc\"\x8f\x01\n\x0cHelloRequest\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\x12\x36\n\x04lang\x18\x03 \x01(\x0e\x32(.org.baeldung.grpc.HelloRequest.Language\"\"\n\x08Language\x12\x06\n\x02\x45N\x10\x00\x12\x06\n\x02\x46R\x10\x01\x12\x06\n\x02\x41R\x10\x02\"!\n\rHelloResponse\x12\x10\n\x08greeting\x18\x01 \x01(\t2\xae\x01\n\x0cHelloService\x12J\n\x05hello\x12\x1f.org.baeldung.grpc.HelloRequest\x1a .org.baeldung.grpc.HelloResponse\x12R\n\x0bhelloStream\x12\x1f.org.baeldung.grpc.HelloRequest\x1a .org.baeldung.grpc.HelloResponse0\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_HELLOREQUEST']._serialized_start=35
  _globals['_HELLOREQUEST']._serialized_end=178
  _globals['_HELLOREQUEST_LANGUAGE']._serialized_start=144
  _globals['_HELLOREQUEST_LANGUAGE']._serialized_end=178
  _globals['_HELLORESPONSE']._serialized_start=180
  _globals['_HELLORESPONSE']._serialized_end=213
  _globals['_HELLOSERVICE']._serialized_start=216
  _globals['_HELLOSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
